name: CI

on:
  push:
    branches: ["main", "master"]
    tags: ["v*", "docs-*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          # Optional test deps if present
          python -m pip install pytest pyyaml

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Smoke test example (no-LLM)
        run: |
          python examples/generate_ofx.py
          test -f examples/transactions.sample.ofx
